# Generated by Django 5.2.1 on 2025-05-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashflow",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
