# Generated by Django 5.2.1 on 2025-05-28 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash", "0003_alter_cashflow_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashflow",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
